Add support for docker registry secret
k3s-io/helm-controller pull request #197
Opened 2023-06-22 22:25 UTC by smbecker

This allows OCI registries to inherit configuration from the configured docker-registry secret

**Linked Issues**
* https://github.com/k3s-io/helm-controller/issues/81

2023-06-26 20:06 UTC, brandond requested changes
One nit about formatting, looks good otherwise.

2023-06-26 20:06 UTC, brandond commented on pkg/apis/helm.cattle.io/v1/types.go
> +	DockerRegistrySecret *corev1.LocalObjectReference  `json:"dockerRegistrySecret,omitempty"`
please make sure that all the files are formatted using `go fmt`. Most editors do this for you but the indentation here appears to be off.

2023-06-27 13:54 UTC, smbecker commented on pkg/apis/helm.cattle.io/v1/types.go
> +	DockerRegistrySecret *corev1.LocalObjectReference  `json:"dockerRegistrySecret,omitempty"`
Should be fixed now

2023-06-27 17:33 UTC, brandond commented
LGTM, but please sign-off your commits for DCO.

2023-06-28 19:01 UTC, smbecker commented
> LGTM, but please sign-off your commits for DCO.

I had to look up what that even meant :laughing:. It should be good now.

2023-06-28 19:04 UTC, brandond approved these changes

2023-06-28 19:05 UTC, merged

2023-06-28 19:07 UTC, smbecker commented
@brandond, do you have any estimate when this will make it into a release?